### ISSUE TITLE
Uploading firmware to Arduino micro

### ISSUE THREAD

**Issue by andreMonkey** [nanpy/nanpy-firmware#24]
Hello!
We got the firmware and example sketch running for the Arduino Uno. 
It works smoothly :)
Now we tried with the Arduino Micro, which we would be needing for our prototype, but cant upload the firmware to the micro. Have you heard of any issues before? 
Error Message when uploading: http://codepad.org/NiDRZDIe

Any help would be much appreciated :)

**Comment by ponty** [comment]
"programmer is not responding"

It seems to be a connection or hardware problem, not related to Nanpy.

**Comment by andreMonkey** [comment]
OK! I will try with a new micro. Thank you for you help!
