### ISSUE TITLE
Error uploading Sketchbook/Nanpy to Arduino UNO

### ISSUE THREAD

**Issue by vsltech** [nanpy/nanpy-firmware#27]
Getting this error kindly check and reply ASAP

Nanpy/freeram.c.o: In function `free_ram3':
/home/pi/sketchbook/libraries/Nanpy/freeram.c:53: multiple definition of `free_ram1'
freeram.c.o:freeram.c:53: first defined here
Nanpy/freeram.c.o: In function `free_ram3':
/home/pi/sketchbook/libraries/Nanpy/freeram.c:64: multiple definition of `free_ram2'
freeram.c.o:freeram.c:64: first defined here
Nanpy/freeram.c.o: In function `free_ram3':
/home/pi/sketchbook/libraries/Nanpy/freeram.c:64: multiple definition of `free_ram3'
freeram.c.o:freeram.c:64: first defined here
Nanpy/RAMClass.cpp.o: In function `nanpy::RAMClass::elaborate(nanpy::MethodDescriptor*)':
/home/pi/sketchbook/libraries/Nanpy/RAMClass.cpp:15: multiple definition of `nanpy::RAMClass::get_firmware_id()'
RAMClass.cpp.o:RAMClass.cpp:15: first defined here
Nanpy/RAMClass.cpp.o: In function `nanpy::RAMClass::elaborate(nanpy::MethodDescriptor*)':
/home/pi/sketchbook/libraries/Nanpy/RAMClass.cpp:19: multiple definition of `nanpy::RAMClass::elaborate(nanpy::MethodDescriptor*)'
RAMClass.cpp.o:RAMClass.cpp:19: first defined here
Nanpy/DefineClass.cpp.o: In function `nanpy::DefineClass::elaborate(nanpy::MethodDescriptor*)':
/home/pi/sketchbook/libraries/Nanpy/DefineClass.cpp:67: multiple definition of `nanpy::DefineClass::get_firmware_id()'
DefineClass.cpp.o:DefineClass.cpp:67: first defined here
Nanpy/DefineClass.cpp.o: In function `nanpy::DefineClass::elaborate(nanpy::MethodDescriptor*)':
/home/pi/sketchbook/libraries/Nanpy/DefineClass.cpp:100: multiple definition of `nanpy::DefineClass::elaborate(nanpy::MethodDescriptor*)'
DefineClass.cpp.o:DefineClass.cpp:100: first defined here
Nanpy/ComChannel.cpp.o: In function `nanpy::ComChannel::available()':
/home/pi/sketchbook/libraries/Nanpy/ComChannel.cpp:158: multiple definition of `nanpy::ComChannel::connect()'
ComChannel.cpp.o:ComChannel.cpp:158: first defined here
Nanpy/ComChannel.cpp.o: In function `nanpy::ComChannel::available()':
/home/pi/sketchbook/libraries/Nanpy/ComChannel.cpp:158: multiple definition of `nanpy::ComChannel::println(String&)'
ComChannel.cpp.o:ComChannel.cpp:158: first defined here
Nanpy/ComChannel.cpp.o: In function `nanpy::ComChannel::available()':
/home/pi/sketchbook/libraries/Nanpy/ComChannel.cpp:162: multiple definition of `nanpy::ComChannel::println(char const*)'
ComChannel.cpp.o:ComChannel.cpp:162: first defined here
Nanpy/ComChannel.cpp.o: In function `nanpy::ComChannel::available()':
/home/pi/sketchbook/libraries/Nanpy/ComChannel.cpp:162: multiple definition of `nanpy::ComChannel::println(int)'
ComChannel.cpp.o:ComChannel.cpp:162: first defined here
Nanpy/ComChannel.cpp.o: In function `nanpy::ComChannel::available()':
/home/pi/sketchbook/libraries/Nanpy/ComChannel.cpp:162: multiple definition of `nanpy::ComChannel::println(unsigned int)'
ComChannel.cpp.o:ComChannel.cpp:162: first defined here
Nanpy/ComChannel.cpp.o: In function `nanpy::ComChannel::available()':
/home/pi/sketchbook/libraries/Nanpy/ComChannel.cpp:162: multiple definition of `nanpy::ComChannel::println(float)'
ComChannel.cpp.o:ComChannel.cpp:162: first defined here
Nanpy/ComChannel.cpp.o: In function `nanpy::ComChannel::available()':
/home/pi/sketchbook/libraries/Nanpy/ComChannel.cpp:162: multiple definition of `nanpy::ComChannel::println(double)'
ComChannel.cpp.o:ComChannel.cpp:162: first defined here
Nanpy/ComChannel.cpp.o: In function `nanpy::ComChannel::available()':
/home/pi/sketchbook/libraries/Nanpy/ComChannel.cpp:162: multiple definition of `nanpy::ComChannel::println(long)'
ComChannel.cpp.o:ComChannel.cpp:162: first defined here
Nanpy/ComChannel.cpp.o: In function `nanpy::ComChannel::available()':
/home/pi/sketchbook/libraries/Nanpy/ComChannel.cpp:162: multiple definition of `nanpy::ComChannel::println(unsigned long)'
ComChannel.cpp.o:ComChannel.cpp:162: first defined here
Nanpy/ComChannel.cpp.o: In function `nanpy::ComChannel::available()':
/home/pi/sketchbook/libraries/Nanpy/ComChannel.cpp:162: multiple definition of `readLineFromSerial(char*)'
ComChannel.cpp.o:ComChannel.cpp:162: first defined here
Nanpy/ComChannel.cpp.o: In function `nanpy::ComChannel::available()':
/home/pi/sketchbook/libraries/Nanpy/ComChannel.cpp:158: multiple definition of `nanpy::ComChannel::read_buffer'
ComChannel.cpp.o:ComChannel.cpp:158: first defined here
Nanpy/ComChannel.cpp.o: In function `nanpy::ComChannel::available()':
/home/pi/sketchbook/libraries/Nanpy/ComChannel.cpp:162: multiple definition of `nanpy::ComChannel::readLine(char*)'
ComChannel.cpp.o:ComChannel.cpp:162: first defined here
Nanpy/ComChannel.cpp.o: In function `nanpy::ComChannel::available()':
/home/pi/sketchbook/libraries/Nanpy/ComChannel.cpp:162: multiple definition of `nanpy::ComChannel::available()'
ComChannel.cpp.o:ComChannel.cpp:162: first defined here
Nanpy/WireClass.cpp.o: In function `nanpy::WireClass::elaborate(nanpy::MethodDescriptor*)':
/home/pi/sketchbook/libraries/Nanpy/WireClass.cpp:15: multiple definition of `nanpy::WireClass::get_firmware_id()'
WireClass.cpp.o:WireClass.cpp:15: first defined here
Nanpy/WireClass.cpp.o: In function `nanpy::WireClass::elaborate(nanpy::MethodDescriptor*)':
/home/pi/sketchbook/libraries/Nanpy/WireClass.cpp:34: multiple definition of `nanpy::WireClass::elaborate(nanpy::MethodDescriptor*)'
WireClass.cpp.o:WireClass.cpp:34: first defined here
Nanpy/InfoClass.cpp.o: In function `nanpy::InfoClass::elaborate(nanpy::MethodDescriptor*)':
/home/pi/sketchbook/libraries/Nanpy/InfoClass.cpp:14: multiple definition of `nanpy::InfoClass::get_firmware_id()'
InfoClass.cpp.o:InfoClass.cpp:14: first defined here
Nanpy/InfoClass.cpp.o: In function `nanpy::InfoClass::elaborate(nanpy::MethodDescriptor*)':
/home/pi/sketchbook/libraries/Nanpy/InfoClass.cpp:20: multiple definition of `nanpy::InfoClass::elaborate(nanpy::MethodDescriptor*)'
InfoClass.cpp.o:InfoClass.cpp:20: first defined here
Nanpy/WatchdogClass.cpp.o: In function `disable_watchdog_at_startup()':
/home/pi/sketchbook/libraries/Nanpy/WatchdogClass.cpp:37: multiple definition of `disable_watchdog_at_startup()'
WatchdogClass.cpp.o:WatchdogClass.cpp:37: first defined here
Nanpy/StepperClass.cpp.o: In function `nanpy::StepperClass::elaborate(nanpy::MethodDescriptor*)':
/home/pi/sketchbook/libraries/Nanpy/StepperClass.cpp:15: multiple definition of `nanpy::StepperClass::get_firmware_id()'
StepperClass.cpp.o:StepperClass.cpp:15: first defined here
Nanpy/StepperClass.cpp.o: In function `nanpy::StepperClass::elaborate(nanpy::MethodDescriptor*)':
/home/pi/sketchbook/libraries/Nanpy/StepperClass.cpp:37: multiple definition of `nanpy::StepperClass::elaborate(nanpy::MethodDescriptor*)'
StepperClass.cpp.o:StepperClass.cpp:37: first defined here
Nanpy/ArduinoClass.cpp.o: In function `nanpy::ArduinoClass::elaborate(nanpy::MethodDescriptor*)':
/home/pi/sketchbook/libraries/Nanpy/ArduinoClass.cpp:11: multiple definition of `nanpy::ArduinoClass::get_firmware_id()'
ArduinoClass.cpp.o:ArduinoClass.cpp:11: first defined here
Nanpy/ArduinoClass.cpp.o: In function `nanpy::ArduinoClass::elaborate(nanpy::MethodDescriptor*)':
/home/pi/sketchbook/libraries/Nanpy/ArduinoClass.cpp:13: multiple definition of `nanpy::ArduinoClass::elaborate(nanpy::MethodDescriptor*)'
ArduinoClass.cpp.o:ArduinoClass.cpp:13: first defined here
Nanpy/ArduinoCoreClass.cpp.o: In function `nanpy::ArduinoCoreClass::elaborate(nanpy::MethodDescriptor*)':
/home/pi/sketchbook/libraries/Nanpy/ArduinoCoreClass.cpp:18: multiple definition of `nanpy::ArduinoCoreClass::get_firmware_id()'
ArduinoCoreClass.cpp.o:ArduinoCoreClass.cpp:18: first defined here
Nanpy/ArduinoCoreClass.cpp.o: In function `nanpy::ArduinoCoreClass::elaborate(nanpy::MethodDescriptor*)':
/home/pi/sketchbook/libraries/Nanpy/ArduinoCoreClass.cpp:38: multiple definition of `nanpy::ArduinoCoreClass::elaborate(nanpy::MethodDescriptor*)'
ArduinoCoreClass.cpp.o:ArduinoCoreClass.cpp:38: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::MethodDescriptor()'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::stack_pool_size'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::stack_pool'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::MethodDescriptor()'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::getNArgs()'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::getBool(int)'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::getInt(int)'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::getByte(int)'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::getFloat(int)'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::getDouble(int)'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::getString(int)'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::getClass()'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::getObjectId()'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::getName()'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::returns(String&)'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::returns(char const*)'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::returns(int)'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::returns(unsigned int)'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::returns(float)'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::returns(double)'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::returns(long)'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/MethodDescriptor.cpp.o: In function `nanpy::MethodDescriptor::returns(unsigned long)':
/home/pi/sketchbook/libraries/Nanpy/MethodDescriptor.cpp:118: multiple definition of `nanpy::MethodDescriptor::returns(unsigned long)'
MethodDescriptor.cpp.o:MethodDescriptor.cpp:118: first defined here
Nanpy/ServoClass.cpp.o: In function `nanpy::ServoClass::elaborate(nanpy::MethodDescriptor*)':
/home/pi/sketchbook/libraries/Nanpy/ServoClass.cpp:15: multiple definition of `nanpy::ServoClass::get_firmware_id()'
ServoClass.cpp.o:ServoClass.cpp:15: first defined here
Nanpy/ServoClass.cpp.o: In function `nanpy::ServoClass::elaborate(nanpy::MethodDescriptor*)':
/home/pi/sketchbook/libraries/Nanpy/ServoClass.cpp:42: multiple definition of `nanpy::ServoClass::elaborate(nanpy::MethodDescriptor*)'
ServoClass.cpp.o:ServoClass.cpp:42: first defined here
Nanpy/BaseClass.cpp.o: In function `_GLOBAL__sub_D__ZN5nanpy8Register7classesE':
/home/pi/sketchbook/libraries/Nanpy/SlimArray.h:86: multiple definition of `nanpy::Register::classes'
BaseClass.cpp.o:SlimArray.h:86: first defined here
collect2: error: ld returned 1 exit status

**Comment by ponty** [comment]
Please read the README:
"Copy Nanpy directory under your "sketchbook" directory,.."

You have copied it under /home/pi/sketchbook/libraries/
