### ISSUE TITLE
new project: nanpy-drivers

### ISSUE THREAD

**Issue by ponty** [nanpy/nanpy-firmware#8]
I started a new project: linux driver for nanpy-firmware
Possible current usage:  I2C or GPIO expander.

https://github.com/ponty/nanpy-drivers

**Comment by astagi** [comment]
looks interesting, wow! I'll have a look at the code asap

On Wed, Jan 21, 2015 at 3:47 PM, ponty <notifications@github.com> wrote:

> Closed #8 <https://github.com/nanpy/nanpy-firmware/issues/8>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nanpy/nanpy-firmware/issues/8#event-222347448>.
>



-- 
Andrea Stagi (@4stagi) - Develover @Nephila
Job profile: http://linkedin.com/in/andreastagi
Website: http://4spills.blogspot.it/
Github: http://github.com/astagi
